In [21]:
import open3d as o3d
import numpy as np

In [2]:
mesh = o3d.io.read_triangle_mesh("cube.obj")
#mesh = o3d.io.read_triangle_mesh("sphere.obj")
#mesh = o3d.io.read_triangle_mesh("tetrahedron.obj")
#mesh = o3d.io.read_triangle_mesh("cow.obj")

#mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh])

In [3]:
v=np.asarray(mesh.vertices)
t=np.asarray(mesh.triangles)

print('Vertices:',v)
print('Triangles:',t)


Vertices: [[ 2.18866205  5.86984015  0.51677299]
 [ 1.79489398  4.83536005  0.48091   ]
 [ 2.717314    6.01616001 -1.116395  ]
 ...
 [-0.92921501  2.70158911 -4.67958117]
 [-0.759368    2.66751289 -4.68555212]
 [-0.72835702  2.64725804 -4.83324718]]
Triangles: [[   0    1    2]
 [   3    2    1]
 [   4    0    5]
 ...
 [1027 1030 1029]
 [1027 1031 1030]
 [1027 1012 1031]]
